# Generated by Django 5.1 on 2024-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('date_posted', models.DateField()),
                ('job_country', models.CharField(max_length=200)),
                ('job_position', models.CharField(max_length=200)),
                ('area_of_expertise', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=200)),
                ('robot_type', models.CharField(max_length=200)),
                ('robotics_domain', models.CharField(max_length=200)),
                ('job_description', models.TextField(max_length=2000)),
            ],
        ),
    ]
