# Generated by Django 5.1 on 2024-12-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(default='robotics', max_length=1000),
            preserve_default=False,
        ),
    ]
