# Generated by Django 5.1 on 2025-01-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_graphdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphAndGraphDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charts', models.FileField(upload_to='')),
                ('description_dictionary', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='GraphDescription',
        ),
    ]
