# Generated by Django 5.1 on 2025-01-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_graphandgraphdescriptions_delete_graphdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_dictionary', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='GraphAndGraphDescriptions',
        ),
    ]
