# Generated by Django 5.1 on 2025-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_graphdescription_delete_graphandgraphdescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(max_length=10)),
                ('graph_file', models.FileField(upload_to='')),
            ],
        ),
    ]
