# Generated by Django 5.1 on 2025-01-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='graph_name',
        ),
    ]
