# Generated by Django 5.1 on 2025-01-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_graphdescription_graph_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdescription',
            name='graph_name',
        ),
        migrations.AddField(
            model_name='graph',
            name='graph_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
