# Generated by Django 5.1 on 2025-01-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_graphdescription_graph_name_graph_graph_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph_file',
            field=models.JSONField(),
        ),
    ]
